spring:
  datasource:
    url: jdbc:postgresql://activiti-postgres:5432/activiti_poc
    username: postgres
    password: 123
  jpa:
    generate-ddl: false

rest:
  url: http://activiti-srv:8081/math/{val}