version: "2"

services:
  activiti-postgres:
    container_name: activiti-postgres
    hostname: activiti-postgres
    networks:
      - activiti
    image: dhr.thprom.ru:5000/postgres:9.5.1-1.pgdg80.1
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
      - ./etc/postgres/activiti.postgres.create.engine.sql:/docker-entrypoint-initdb.d/activiti.postgres.create.engine.sql
      - ./etc/postgres/activiti.postgres.create.history.sql:/docker-entrypoint-initdb.d/activiti.postgres.create.history.sql
      - ./etc/postgres/activiti.postgres.create.identity.sql:/docker-entrypoint-initdb.d/activiti.postgres.create.identity.sql
    environment:
      - POSTGRES_DB=activiti_poc
      - POSTGRES_PASSWORD=123
    expose:
      - 5432
    ports:
      - "5432:5432"

  activiti-app:
    container_name: activiti-app
    hostname: activiti-app
    networks:
      - activiti
    image: "dhr.thprom.ru:5000/activiti.app:${MVN_PROJECT_VERSION}"
    links:
      - activiti-postgres
      - activiti-srv
    volumes:
      - ./etc/app/:/etc/app/
      - ./data/app/:/tmp/logs/
    expose:
      - 8080
    ports:
      - "8080:8080"

  activiti-srv:
    container_name: activiti-srv
    hostname: activiti-srv
    networks:
      - activiti
    image: "dhr.thprom.ru:5000/activiti.srv:${MVN_PROJECT_VERSION}"
    links:
      - activiti-postgres
    volumes:
      - ./etc/srv/:/etc/srv/
      - ./data/srv/:/tmp/logs/
    expose:
      - 8081
    ports:
      - "8081:8081"

  activiti-explorer:
    container_name: activiti-explorer
    hostname: activiti-explorer
    networks:
      - activiti
    image: "dhr.thprom.ru:5000/activiti-explorer:5.22.0"
    links:
      - activiti-postgres
    volumes:
      - ./activiti-explorer/:/usr/local/tomcat/webapps/activiti-explorer
      - ./data/explorer/:/opt/tomcat/logs/
    expose:
      - 8080
    ports:
      - "8090:8080"

networks:
  activiti:
    # Use the overlay driver for multi-host communication
    driver: bridge